on:
  push

jobs:
  auto-deploy:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Trigger pre-release deploy
        run: gh workflow run deploy.yml -f environment=pre-release -f version=v2024.1.1
