on:
  push:

jobs:
  check-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check Docker Compose
        run: docker-compose --version