on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        options:
          - dev
          - pre-release
          - prod
      version:
        description: Version
        required: true
        default: "v2024"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: get head_commit
        run: |
          curl -s -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/${{ github.repository }}/commits/${{ github.events.inputs.environment }}
      - name: echo
        run: echo "<${{ github.event.head_commit.url }}|${{ github.event.head_commit.message }}> by ${{ github.event.head_commit.author.name }} • <${{ github.event.compare }}|Changes>"
