on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment
        options:
          - dev
          - pre-release
          - prod
      version:
        description: Version
        required: true
        default: "v20"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "<${{ github.event.head_commit.url }}|${{ github.event.head_commit.message }}> by ${{ github.event.head_commit.author.name }} • <${{ github.event.compare }}|Changes>"
